import assert from 'node:assert/strict';
import { installBrowser } from '../tools/shots/browser.mjs';
import { Vector3, PerspectiveCamera } from '../src/engine/index.js';
import { StoryUI } from '../src/story/StoryUI.js';
Object.defineProperty( globalThis, 'navigator', { value: {}, configurable: true } );
installBrowser( { search: '', width: 1280, height: 720, root: 'public' } );
const ui = new StoryUI(), camera = new PerspectiveCamera( 70, 16 / 9, 0.1, 5000 );
ui.setObjective( 'Go to the station' );
const target = { id: 'station', label: 'Light station', at: new Vector3( 0, 0, - 50 ) };
ui.guidance( target, camera ); const until = ui._guidePingUntil;
assert.ok( until > performance.now(), 'first appearance starts a finite ping' );
target.at.x = 1; ui.guidance( target, camera ); assert.equal( ui._guidePingUntil, until, 'moving targets do not restart the ping' );
ui.guidance( null, camera ); ui.guidance( target, camera ); assert.equal( ui._guidePingUntil, until, 'temporary hiding does not replay the same destination' );
target.id = 'door'; ui.guidance( target, camera ); assert.notEqual( ui._guideKey, 'Go to the station|station', 'new route threshold pings' );
const firstKey = ui._guideKey; ui.setObjective( 'Return to the house' ); ui.guidance( target, camera );
assert.notEqual( ui._guideKey, firstKey, 'a new objective reusing a door still pings' );
ui._guidePingUntil = performance.now() - 1; ui.guidance( target, camera );
assert.equal( ui.guideEl.classList.contains( 'is-pinging' ), false, 'arrival cue settles back to a quiet marker' );
console.log( 'PASS waypoint arrival cue: finite first appearance, route/objective changes, no motion/hide retriggers and quiet settled state.' );
